// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowHub.Data.Persistence;

#nullable disable

namespace WorkflowHub.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("WorkflowHub.Data.Entities.RefreshToken", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DeviceInfo")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<bool>("IsUsed")
                .HasColumnType("boolean");

            b.Property<DateTime?>("RevokedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("TokenHash");

            b.HasIndex("UserId");

            b.HasIndex("UserId", "RevokedAtUtc", "IsUsed");

            b.ToTable("refresh_tokens", (string)null);
        });

        modelBuilder.Entity("WorkflowHub.Data.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("AvatarUrl")
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)");

            b.Property<string>("Bio")
                .HasMaxLength(160)
                .HasColumnType("character varying(160)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DisplayName")
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<string>("Role")
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<string>("Team")
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<string>("Username")
                .HasMaxLength(30)
                .HasColumnType("character varying(30)");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnType("character varying(320)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("SecurityStamp")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.HasIndex("Username")
                .IsUnique()
                .HasFilter("\"Username\" IS NOT NULL");

            b.ToTable("users", (string)null);
        });

        modelBuilder.Entity("WorkflowHub.Data.Entities.UserIdentity", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("LastLoginAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Provider")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("ProviderAvatarUrl")
                .HasMaxLength(2048)
                .HasColumnType("character varying(2048)");

            b.Property<string>("ProviderEmail")
                .HasMaxLength(320)
                .HasColumnType("character varying(320)");

            b.Property<string>("ProviderSub")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.HasIndex("Provider", "ProviderSub")
                .IsUnique();

            b.HasIndex("UserId", "Provider")
                .IsUnique();

            b.ToTable("user_identities", (string)null);
        });

        modelBuilder.Entity("WorkflowHub.Data.Entities.RefreshToken", b =>
        {
            b.HasOne("WorkflowHub.Data.Entities.User", "User")
                .WithMany("RefreshTokens")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("User");
        });

        modelBuilder.Entity("WorkflowHub.Data.Entities.UserIdentity", b =>
        {
            b.HasOne("WorkflowHub.Data.Entities.User", "User")
                .WithMany("Identities")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("User");
        });

        modelBuilder.Entity("WorkflowHub.Data.Entities.User", b =>
        {
            b.Navigation("Identities");

            b.Navigation("RefreshTokens");
        });
    }
}
